-- The guild message of the day window (Toolbox.Motd).
local H = require("harness")

return function(t)
  local function text() return H.motd():Find("motd_text").text end

  t.test("NewMessage: only a real, unseen message in a guild", function()
    H.boot()
    local N = Toolbox.Motd.NewMessage
    t.eq(N(nil, ""), nil, "no character")
    t.eq(N({ inGuild = false, guildMotd = "Hi" }, ""), nil, "not in a guild")
    t.eq(N({ inGuild = true, guildMotd = "" }, ""), nil, "empty (not loaded yet)")
    t.eq(N({ inGuild = true, guildMotd = "   " }, ""), nil, "only spaces")
    t.eq(N({ inGuild = true }, ""), nil, "missing")
    t.eq(N({ inGuild = true, guildMotd = "Raid at 8" }, ""), "Raid at 8")
    t.eq(N({ inGuild = true, guildMotd = "Raid at 8" }, "Raid at 8"), nil, "already seen")
    t.eq(N({ inGuild = true, guildMotd = " Raid at 8\n" }, "Raid at 8"), nil, "spacing isn't a change")
    t.eq(N({ inGuild = true, guildMotd = "Raid at 9" }, "Raid at 8"), "Raid at 9")
  end)

  t.test("no guild: no window", function()
    H.boot()
    H.advance(3)
    t.eq(H.motd(), nil)
  end)

  t.test("a message that loads after login opens the window once", function()
    H.boot()
    H.setGuild("Knights", "")
    H.advance(2)
    t.eq(H.motd(), nil, "empty while the guild data loads")
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    t.ok(H.motd():IsShown())
    t.eq(text(), "Raid at 8")
    t.eq(H.motd():Find("motd_guild").text, "Knights")
    t.eq(H.saved("guild_motd").seen, "Raid at 8")
    H.click("toolbox_motd", "motd_ok")
    t.no(H.motd():IsShown())
    H.advance(5)
    t.no(H.motd():IsShown(), "not again in the same session")
  end)

  t.test("an unchanged message stays hidden after a reload and a restart", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    H.closeWindow("toolbox_motd")
    H.reload()
    H.advance(2)
    t.no(H.motd() and H.motd():IsShown(), "reload")
    H.restart(nil, true)
    H.advance(2)
    t.no(H.motd() and H.motd():IsShown(), "restart")
  end)

  t.test("a changed message shows at the next reload", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    H.closeWindow("toolbox_motd")
    H.S.social.guildMotd = "Raid moved to 9"
    H.reload()
    t.ok(H.motd():IsShown(), "shown from ShroudOnStart")
    t.eq(text(), "Raid moved to 9")
  end)

  t.test("a change while playing shows at once", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    H.closeWindow("toolbox_motd")
    H.setMotd("Siege tonight")
    t.ok(H.motd():IsShown())
    t.eq(text(), "Siege tonight")
  end)

  t.test("a refused window is retried and not marked seen", function()
    H.boot()
    H.S.showRefused = true
    H.setGuild("Knights", "Raid at 8")
    H.advance(2)
    t.no(H.motd():IsShown())
    t.eq(H.saved("guild_motd"), nil, "not seen yet")
    H.S.showRefused = false
    H.advance(1)
    t.ok(H.motd():IsShown())
    t.eq(H.saved("guild_motd").seen, "Raid at 8")
  end)

  t.test("each character remembers its own message", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    H.closeWindow("toolbox_motd")
    H.S.char.name = "Alt"
    H.advance(1)
    t.ok(H.motd():IsShown(), "new to the alt")
  end)

  t.test("off: nothing opens by itself, /tbx motd still shows it", function()
    H.boot()
    H.chat("/tbx motd off")
    t.eq(H.saved("guild_motd").show, false)
    H.setGuild("Knights", "Raid at 8")
    H.advance(2)
    t.eq(H.motd(), nil)
    H.chat("/tbx motd")
    t.ok(H.motd():IsShown())
    t.eq(text(), "Raid at 8")
    H.reload()
    t.no(H.motd() and H.motd():IsShown(), "stays off, and it was seen")
  end)

  t.test("/tbx motd outside a guild says so", function()
    H.boot()
    H.clearLogs()
    H.chat("/tbx motd")
    t.ok(H.logged("not in a guild"))
    H.setGuild("Knights", "")
    H.chat("/tbx motd")
    t.ok(H.logged("no message of the day"))
  end)

  t.test("settings toggle follows the command and turns it off", function()
    H.boot()
    H.chat("/tbx config")
    local box = H.config():Find("guild_motd")
    t.eq(box.value, true, "on by default")
    H.chat("/tbx motd off")
    t.eq(box.value, false)
    H.change("toolbox_config", "guild_motd", true)
    t.eq(Toolbox.Motd.GetShow(), true)
    t.eq(H.saved("guild_motd").show, true)
  end)
end
