-- Hovering the compact window pops up the Session XP window.
local H = require("harness")

return function(t)
  local SHOW, HIDE = 0.5, 0.75
  local function setup()
    H.boot()
    H.chat("/tbx xp")
    SHOW, HIDE = Toolbox.Hover.SHOW_DELAY, Toolbox.Hover.HIDE_DELAY
  end
  local function xpShown() return H.window():IsShown() end

  t.test("pop-up appears after the delay, not before", function()
    setup()
    H.hover("toolbox_compact", nil, true)
    H.advance(SHOW - 0.2, 0.1)
    t.no(xpShown(), "not yet")
    H.advance(0.3, 0.1)
    t.ok(xpShown(), "after the delay")
  end)

  t.test("passing over quickly does nothing", function()
    setup()
    H.hover("toolbox_compact", nil, true)
    H.advance(SHOW / 2, 0.1)
    H.hover("toolbox_compact", nil, false)
    H.advance(2, 0.1)
    t.no(xpShown())
  end)

  t.test("pop-up closes after the pointer leaves", function()
    setup()
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    H.hover("toolbox_compact", nil, false)
    H.advance(HIDE - 0.2, 0.1)
    t.ok(xpShown(), "grace period")
    H.advance(0.4, 0.1)
    t.no(xpShown(), "closed")
  end)

  t.test("pop-up stays while the pointer is over it, so Reset can be clicked", function()
    setup()
    H.gain(500, 0)
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    H.hover("toolbox_compact", nil, false)
    H.advance(0.3, 0.1)                       -- crossing the gap
    H.hover("toolbox_xp", nil, true)
    H.hover("toolbox_xp", "header", true)
    H.advance(3, 0.1)
    t.ok(xpShown(), "still up while over it")
    H.click("toolbox_xp", "reset")
    t.eq(Toolbox.XP.Gained(Toolbox.session, "a"), 0, "reset worked")
    H.hover("toolbox_xp", "header", false)
    H.hover("toolbox_xp", nil, false)
    H.advance(1, 0.1)
    t.no(xpShown(), "closed after leaving both")
  end)

  t.test("moving between a window and its children doesn't flicker", function()
    setup()
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    -- a host that reports leaving the parent when entering a child
    H.hover("toolbox_compact", "body", true)
    H.hover("toolbox_compact", nil, false)
    H.advance(2, 0.1)
    t.ok(xpShown())
  end)

  t.test("a pop-up is not remembered as open", function()
    setup()
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    t.ok(xpShown())
    t.eq(H.saved("window").open, false)
    H.reload()
    t.no(xpShown(), "not reopened after reload")
  end)

  t.test("a pinned Session XP window is left alone", function()
    setup()
    H.chat("/tbx xpdetailed")
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    H.hover("toolbox_compact", nil, false)
    H.advance(2, 0.1)
    t.ok(xpShown(), "still open")
    t.eq(H.saved("window").open, true)
  end)

  t.test("/tbx xpdetailed pins a popped-up window", function()
    setup()
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    H.chat("/tbx xpdetailed")
    t.eq(H.saved("window").open, true)
    H.hover("toolbox_compact", nil, false)
    H.advance(2, 0.1)
    t.ok(xpShown(), "pinned, so it stays")
    H.chat("/tbx xpdetailed")
    t.no(xpShown(), "and /tbx xpdetailed closes it again")
  end)

  t.test("the settings checkbox turns hover off and it is remembered", function()
    setup()
    H.chat("/tbx config")
    t.eq(H.config():Find("hover_popup").value, true, "on by default")
    H.change("toolbox_config", "hover_popup", false)
    H.hover("toolbox_compact", nil, true)
    H.advance(2, 0.1)
    t.no(xpShown())
    t.eq(H.saved("compact").hover, false)
    H.reload()
    t.eq(Toolbox.Compact.GetHover(), false)
  end)

  t.test("turning hover off closes an open pop-up", function()
    setup()
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    Toolbox.Compact.SetHover(false)
    t.no(xpShown())
  end)

  t.test("a refused Show() fails quietly", function()
    setup()
    H.S.showRefused = true
    H.clearLogs()
    H.hover("toolbox_compact", nil, true)
    H.advance(2, 0.1)
    t.no(xpShown())
    t.eq(#H.logs(), 0, "no chat spam")
  end)

  t.test("closing the pop-up with its X clears its hover state", function()
    setup()
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    H.hover("toolbox_compact", nil, false)
    H.hover("toolbox_xp", nil, true)
    H.closeWindow("toolbox_xp")
    t.no(xpShown())
    t.eq(H.saved("window").open, false)
    -- hovering the compact window again works normally
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    t.ok(xpShown())
  end)

  t.test("hover state is dropped when the compact window closes", function()
    setup()
    H.hover("toolbox_compact", nil, true)
    H.advance(1, 0.1)
    H.chat("/tbx xp")                  -- closed while the pointer was on it
    H.advance(2, 0.1)
    t.no(xpShown(), "pop-up closed too")
  end)
end
