-- Slash command registration and dispatch.
local H = require("harness")

return function(t)
  t.test("both commands are registered from ShroudOnStart", function()
    H.boot()
    t.ok(H.S.commands.toolbox, "/toolbox")
    t.ok(H.S.commands.tbx, "/tbx")
    t.eq(H.S.commands.toolbox, H.S.commands.tbx, "one dispatcher")
  end)

  t.test("constructors raise at file top level (harness enforces it)", function()
    H.boot()
    t.raises(function() Shroud.Command{ name = "x", help = "x", run = print } end, "outside a callback")
    t.raises(function() Shroud.UI.Label{ text = "x" } end, "outside a callback")
  end)

  t.test("a refused registration is reported in chat", function()
    H.boot()
    H.S.taken.tbx = "taken"
    H.S.taken.toolbox = "tooCloseToChat"
    H.clearLogs()
    H.reload()
    t.ok(H.logged("/tbx: taken"), "taken reported")
    t.ok(H.logged("/toolbox: tooCloseToChat"), "tooCloseToChat reported")
  end)

  t.test("help lists every command", function()
    H.boot()
    H.clearLogs()
    H.chat("/toolbox help")
    t.ok(H.logged("help"))
    t.ok(H.logged("/toolbox xp"))
    t.ok(H.logged("/toolbox reset"))
    t.ok(H.logged("/toolbox font"))
    t.ok(H.logged("/tbx"), "mentions the alias")
  end)

  t.test("no arguments shows help", function()
    H.boot()
    H.clearLogs()
    H.chat("/tbx")
    t.ok(H.logged("/toolbox reset"))
  end)

  t.test("xp toggles the window, alias and case-insensitive", function()
    H.boot()
    t.no(H.window():IsShown(), "starts closed")
    H.chat("/toolbox xp")
    t.ok(H.window():IsShown())
    H.chat("/tbx   XP  ")
    t.no(H.window():IsShown())
  end)

  t.test("reset starts a new session", function()
    H.boot()
    H.gain(5000, 100)
    H.advance(60)
    t.eq(Toolbox.XP.Gained(Toolbox.session, "a"), 5000)
    H.clearLogs()
    H.chat("/tbx reset")
    t.ok(H.logged("New XP session"))
    t.eq(Toolbox.XP.Gained(Toolbox.session, "a"), 0)
    t.eq(Toolbox.session.start, ShroudTime)
  end)

  t.test("unknown subcommand", function()
    H.boot()
    H.clearLogs()
    t.no(Toolbox.Dispatch("frobnicate"))
    t.ok(H.logged("Unknown command 'frobnicate'"))
  end)

  t.test("argument parsing", function()
    H.boot()
    local w, rest = Toolbox.ParseArgs("  Reset   now please ")
    t.eq(w, "reset")
    t.eq(rest, "now please")
    w, rest = Toolbox.ParseArgs(nil)
    t.eq(w, "")
    t.eq(rest, "")
  end)
end
