-- The compact XP window (/toolbox compact) and the one-hour window behind it.
local H = require("harness")

return function(t)
  t.test("last hour: whole session while younger than an hour", function()
    H.boot(nil, 0)
    local X = Toolbox.XP
    local s = X.NewSession(0, 0, 0, "A")
    X.Record(s, 600, 1000, 50)
    X.Record(s, 1800, 3000, 50)
    t.eq(X.LastHour(s, "a", 1800), 3000)
    t.eq(X.LastHour(s, "p", 1800), 50)
  end)

  t.test("last hour: drops gains older than an hour", function()
    H.boot(nil, 0)
    local X = Toolbox.XP
    local s = X.NewSession(0, 0, 0, "A")
    X.Record(s, 100, 5000, 0)       -- will fall out of the hour
    X.Record(s, 3000, 7000, 0)      -- inside it
    t.eq(X.LastHour(s, "a", 3700), 2000)
    t.eq(X.LastHour(s, "a", 6700), 0, "nothing in the last hour")
    t.eq(X.Gained(s, "a"), 7000, "session total unaffected")
  end)

  t.test("10-minute rate unchanged by the longer history", function()
    H.boot(nil, 0)
    local X = Toolbox.XP
    local s = X.NewSession(0, 0, 0, "A")
    for sec = 10, 3600, 10 do X.Record(s, sec, sec, 0) end    -- 1 XP/s for an hour
    t.near(X.WindowRate(s, "a", 3600), 3600, 1)
    t.near(X.LastHour(s, "a", 3600), 3600, 1)
  end)

  t.test("compact toggles, starts closed", function()
    H.boot()
    t.no(H.compact():IsShown())
    H.chat("/tbx xp")
    t.ok(H.compact():IsShown())
    H.chat("/toolbox xp")
    t.no(H.compact():IsShown())
  end)

  t.test("compact shows session time, pools and last hour", function()
    H.boot(nil, 0)
    H.chat("/tbx xp")
    H.gain(12000, 300)
    H.advance(125)
    t.eq(H.compactText("elapsed"), "Session 2m 05s")
    t.eq(H.compactText("a_pool_label"), "Adv pool")
    t.eq(H.compactText("a_pool"), "37,000")          -- 25,000 + 12,000
    t.eq(H.compactText("a_hour_label"), "Last hour")
    t.eq(H.compactText("a_hour"), "+12,000")
    t.eq(H.compactText("p_pool_label"), "Prod pool")
    t.eq(H.compactText("p_pool"), "4,300")
    t.eq(H.compactText("p_hour"), "+300")
  end)

  t.test("pool shows what the game reports, even after spending it", function()
    H.boot()
    H.chat("/tbx xp")
    H.gain(5000, 0)
    H.S.char.advPool = 100               -- player trained skills with the pool
    H.advance(1)
    t.eq(H.compactText("a_pool"), "100")
    t.eq(H.compactText("a_hour"), "+5,000", "earned XP comes from totals, not the pool")
  end)

  t.test("compact open state and position survive reload", function()
    H.boot()
    H.chat("/tbx xp")
    H.moveWindow("toolbox_compact", 900, 40)
    H.advance(1)
    H.reload()
    t.ok(H.compact():IsShown())
    t.eq(H.compact().x, 900)
    t.eq(H.compact().y, 40)
    t.eq(H.saved("compact").open, true)
  end)

  t.test("compact close button is remembered and syncs settings", function()
    H.boot()
    H.chat("/tbx config")
    H.chat("/tbx xp")
    t.eq(H.config():Find("xp_mode").value, "Window")
    H.closeWindow("toolbox_compact")
    t.eq(H.saved("compact").open, false)
    t.eq(H.config():Find("xp_mode").value, "Hidden")
  end)

  t.test("settings: XP window Hidden / Window / HUD strip", function()
    H.boot()
    H.chat("/tbx config")
    H.change("toolbox_config", "xp_mode", "Window")
    t.ok(H.compact():IsShown())
    H.change("toolbox_config", "xp_mode", "HUD strip")
    t.no(H.compact():IsShown(), "the window hides for the strip")
    t.eq(H.S.frames.toolbox_xp_hud.visible, true)
    H.change("toolbox_config", "xp_mode", "Hidden")
    t.eq(H.S.frames.toolbox_xp_hud.visible, false)
    t.eq(H.saved("compact").open, false)
    t.eq(H.saved("compact").hud, true, "the form is remembered for next time")
  end)

  t.test("compact follows the text size", function()
    H.boot()
    H.chat("/tbx xp")
    H.chat("/tbx font 15")
    t.eq(H.compact():Find("a_pool").style.fontSize, 15)
    t.eq(H.compact():Find("elapsed").style.fontSize, 15)
    H.reload()
    t.eq(H.compact():Find("p_hour_label").style.fontSize, 15, "built with the saved size")
  end)

  t.test("both windows can be open at once", function()
    H.boot()
    H.chat("/tbx xpdetailed")
    H.chat("/tbx xp")
    t.ok(H.window():IsShown())
    t.ok(H.compact():IsShown())
  end)

  t.test("session state is stored once per tick, not per XP event", function()
    H.boot()
    local stored = H.saved("session")
    for _ = 1, 5 do H.gain(10, 0) end
    t.eq(H.saved("session"), stored, "not stored by the callbacks")
    H.advance(1)
    t.ok(H.saved("session") ~= stored, "stored on the tick")
    t.eq(H.saved("session").samples[#H.saved("session").samples].a, H.S.char.adv)
  end)
  t.test("compact window (API 19): from settings and chat, rebuilt open, kept after a reload", function()
    H.boot()
    H.chat("/tbx config")
    H.change("toolbox_config", "xp_mode", "Compact window")
    local w = H.S.windows.toolbox_compact
    t.eq(w.compact, true, "built compact")
    t.eq(w:IsShown(), true, "and open")
    t.eq(H.config():Find("xp_mode").value, "Compact window")
    t.eq(Toolbox.Compact.GetCompact(), true)
    H.advance(1)
    t.ok(w:Find("elapsed").text:find("^Session"), "it shows the session like the window")
    H.reload()
    t.eq(H.S.windows.toolbox_compact.compact, true, "saved")
    t.eq(H.S.windows.toolbox_compact:IsShown(), true)
    H.chat("/tbx xp window")
    t.eq(H.S.windows.toolbox_compact.compact, false, "back to a normal window")
    t.eq(H.S.windows.toolbox_compact:IsShown(), true)
    H.chat("/tbx xp compact")
    t.eq(H.S.windows.toolbox_compact.compact, true)
    H.chat("/tbx xp hud")
    t.eq(Toolbox.Compact.GetHud(), true)
    t.eq(H.S.windows.toolbox_compact:IsShown(), false, "the HUD strip instead")
    H.chat("/tbx config")
    t.eq(H.config():Find("xp_mode").value, "HUD strip")
    H.change("toolbox_config", "xp_mode", "Compact window")
    t.eq(Toolbox.Compact.GetHud(), false)
    t.eq(H.S.windows.toolbox_compact:IsShown(), true)
  end)

  t.test("Today as a compact window; hovering it still pops up Today Detailed", function()
    H.boot()
    H.chat("/tbx daily")                          -- open; the form commands keep open / closed as it is
    H.chat("/tbx daily compact")
    local w = H.S.windows.toolbox_daily
    t.eq(w.compact, true)
    t.eq(w:IsShown(), true)
    H.hover("toolbox_daily", nil, true)
    H.advance(2)
    t.ok(H.detail() and H.detail():IsShown(), "the hover pop-up")
  end)
end
