-- The compact XP window (/toolbox compact) and the one-hour window behind it.
local H = require("harness")

return function(t)
  t.test("last hour: whole session while younger than an hour", function()
    H.boot(nil, 0)
    local X = Toolbox.XP
    local s = X.NewSession(0, 0, 0, "A")
    X.Record(s, 600, 1000, 50)
    X.Record(s, 1800, 3000, 50)
    t.eq(X.LastHour(s, "a", 1800), 3000)
    t.eq(X.LastHour(s, "p", 1800), 50)
  end)

  t.test("last hour: drops gains older than an hour", function()
    H.boot(nil, 0)
    local X = Toolbox.XP
    local s = X.NewSession(0, 0, 0, "A")
    X.Record(s, 100, 5000, 0)       -- will fall out of the hour
    X.Record(s, 3000, 7000, 0)      -- inside it
    t.eq(X.LastHour(s, "a", 3700), 2000)
    t.eq(X.LastHour(s, "a", 6700), 0, "nothing in the last hour")
    t.eq(X.Gained(s, "a"), 7000, "session total unaffected")
  end)

  t.test("10-minute rate unchanged by the longer history", function()
    H.boot(nil, 0)
    local X = Toolbox.XP
    local s = X.NewSession(0, 0, 0, "A")
    for sec = 10, 3600, 10 do X.Record(s, sec, sec, 0) end    -- 1 XP/s for an hour
    t.near(X.WindowRate(s, "a", 3600), 3600, 1)
    t.near(X.LastHour(s, "a", 3600), 3600, 1)
  end)

  t.test("compact toggles, starts closed", function()
    H.boot()
    t.no(H.compact():IsShown())
    H.chat("/tbx compact")
    t.ok(H.compact():IsShown())
    H.chat("/toolbox compact")
    t.no(H.compact():IsShown())
  end)

  t.test("compact shows session time, pools and last hour", function()
    H.boot(nil, 0)
    H.chat("/tbx compact")
    H.gain(12000, 300)
    H.advance(125)
    t.eq(H.compactText("elapsed"), "Session 2m 05s")
    t.eq(H.compactText("a_pool_label"), "Adv pool")
    t.eq(H.compactText("a_pool"), "37,000")          -- 25,000 + 12,000
    t.eq(H.compactText("a_hour_label"), "Last hour")
    t.eq(H.compactText("a_hour"), "+12,000")
    t.eq(H.compactText("p_pool_label"), "Prod pool")
    t.eq(H.compactText("p_pool"), "4,300")
    t.eq(H.compactText("p_hour"), "+300")
  end)

  t.test("pool shows what the game reports, even after spending it", function()
    H.boot()
    H.chat("/tbx compact")
    H.gain(5000, 0)
    H.S.char.advPool = 100               -- player trained skills with the pool
    H.advance(1)
    t.eq(H.compactText("a_pool"), "100")
    t.eq(H.compactText("a_hour"), "+5,000", "earned XP comes from totals, not the pool")
  end)

  t.test("compact open state and position survive reload", function()
    H.boot()
    H.chat("/tbx compact")
    H.moveWindow("toolbox_compact", 900, 40)
    H.advance(1)
    H.reload()
    t.ok(H.compact():IsShown())
    t.eq(H.compact().x, 900)
    t.eq(H.compact().y, 40)
    t.eq(H.saved("compact").open, true)
  end)

  t.test("compact close button is remembered and syncs settings", function()
    H.boot()
    H.chat("/tbx config")
    H.chat("/tbx compact")
    t.eq(H.config():Find("show_compact").value, true)
    H.closeWindow("toolbox_compact")
    t.eq(H.saved("compact").open, false)
    t.eq(H.config():Find("show_compact").value, false)
  end)

  t.test("settings checkbox opens the compact window", function()
    H.boot()
    H.chat("/tbx config")
    H.change("toolbox_config", "show_compact", true)
    t.ok(H.compact():IsShown())
  end)

  t.test("compact follows the text size", function()
    H.boot()
    H.chat("/tbx compact")
    H.chat("/tbx font 15")
    t.eq(H.compact():Find("a_pool").style.fontSize, 15)
    t.eq(H.compact():Find("elapsed").style.fontSize, 15)
    H.reload()
    t.eq(H.compact():Find("p_hour_label").style.fontSize, 15, "built with the saved size")
  end)

  t.test("both windows can be open at once", function()
    H.boot()
    H.chat("/tbx xp")
    H.chat("/tbx compact")
    t.ok(H.window():IsShown())
    t.ok(H.compact():IsShown())
  end)

  t.test("session state is stored once per tick, not per XP event", function()
    H.boot()
    local stored = H.saved("session")
    for _ = 1, 5 do H.gain(10, 0) end
    t.eq(H.saved("session"), stored, "not stored by the callbacks")
    H.advance(1)
    t.ok(H.saved("session") ~= stored, "stored on the tick")
    t.eq(H.saved("session").samples[#H.saved("session").samples].a, H.S.char.adv)
  end)
end
