-- Notifications (Toolbox.Notify): the guild message of the day, mail and the other game notices.
local H = require("harness")

return function(t)
  local function seen(key)
    local saved = H.saved("notify")
    return saved and saved.sources[key].seen
  end

  -- Booted and past the start-up settling, so counts going down are remembered.
  local function settled()
    H.boot()
    H.advance(Toolbox.Notify.SETTLE + 1)
  end

  -- guild message of the day ------------------------------------------------

  t.test("NewMotd: only a real, unseen message in a guild", function()
    H.boot()
    local N = Toolbox.Notify.NewMotd
    t.eq(N(nil, ""), nil, "no character")
    t.eq(N({ inGuild = false, guildMotd = "Hi" }, ""), nil, "not in a guild")
    t.eq(N({ inGuild = true, guildMotd = "" }, ""), nil, "empty (not loaded yet)")
    t.eq(N({ inGuild = true, guildMotd = "   " }, ""), nil, "only spaces")
    t.eq(N({ inGuild = true }, ""), nil, "missing")
    t.eq(N({ inGuild = true, guildMotd = "Raid at 8" }, ""), "Raid at 8")
    t.eq(N({ inGuild = true, guildMotd = "Raid at 8" }, "Raid at 8"), nil, "already seen")
    t.eq(N({ inGuild = true, guildMotd = " Raid at 8\n" }, "Raid at 8"), nil, "spacing isn't a change")
    t.eq(N({ inGuild = true, guildMotd = "Raid at 9" }, "Raid at 8"), "Raid at 9")
  end)

  t.test("nothing new: no window", function()
    H.boot()
    H.advance(3)
    t.eq(H.notify(), nil)
  end)

  t.test("a guild message that loads after login shows once", function()
    H.boot()
    H.setGuild("Knights", "")
    H.advance(2)
    t.eq(H.notify(), nil, "empty while the guild data loads")
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    local n = H.notice("motd")
    t.ok(n.shown)
    t.eq(n.text, "Raid at 8")
    t.eq(n.title, "Knights: message of the day")
    t.eq(seen("motd"), "Raid at 8")
    H.click("toolbox_notify", "n_ok")
    t.no(H.notify():IsShown())
    H.advance(5)
    t.no(H.notify():IsShown(), "not again in the same session")
  end)

  t.test("an unchanged guild message stays hidden after a reload and a restart", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    H.closeWindow("toolbox_notify")
    H.reload()
    H.advance(2)
    t.no(H.notify() and H.notify():IsShown(), "reload")
    H.restart(nil, true)
    H.advance(2)
    t.no(H.notify() and H.notify():IsShown(), "restart")
  end)

  t.test("a changed guild message shows at the next reload, or at once while playing", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    H.closeWindow("toolbox_notify")
    H.S.social.guildMotd = "Raid moved to 9"
    H.reload()
    t.ok(H.notice("motd").shown, "shown from ShroudOnStart")
    t.eq(H.notice("motd").text, "Raid moved to 9")
    H.closeWindow("toolbox_notify")
    H.setMotd("Siege tonight")
    t.eq(H.notice("motd").text, "Siege tonight")
  end)

  t.test("API 18: the guild message's own getter and event (the summary's copy can lag)", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    H.closeWindow("toolbox_notify")
    H.guildMotdChanged("Siege tonight")               -- the summary still says "Raid at 8"
    t.ok(H.notice("motd").shown, "shown at once, from the event")
    t.eq(H.notice("motd").text, "Siege tonight")
    t.eq(seen("motd"), "Siege tonight")
    H.closeWindow("toolbox_notify")
    H.advance(2)
    t.no(H.notify():IsShown(), "not again: the getter is read each check, not the stale summary")
  end)

  t.test("an older client without the getter uses the social summary", function()
    H.boot()
    H.S.noGuildMotd = true
    H.reload()
    t.eq(ShroudGetGuildMotd, nil)
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    t.eq(H.notice("motd").text, "Raid at 8")
  end)

  t.test("chat delivery and the notification sound, from settings and chat", function()
    H.boot()
    H.S.files["toolbox/notify.ogg"] = true
    H.reload()
    H.advance(2)
    t.eq(Toolbox.Sounds.Status("notify"), "ready", "the shipped sound loads")
    H.chat("/tbx config")
    local drop = H.config():Find("notify_motd_via")
    t.eq(drop.value, "Window")
    t.eq(table.concat(drop.choices, "|"), "Window|Window + sound|HUD|HUD + sound|Chat|Chat + sound")
    H.change("toolbox_config", "notify_motd_via", "Chat + sound")
    t.eq(Toolbox.Notify.GetVia("motd"), "chat")
    t.eq(Toolbox.Notify.GetSound("motd"), true)
    H.clearLogs()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    t.ok(H.logged("Knights: message of the day: Raid at 8"), H.lastLog())
    t.no(H.notify() and H.notify():IsShown(), "no window")
    t.ok(H.playedNames():find("notify$"), "and the sound: " .. H.playedNames())
    t.eq(seen("motd"), "Raid at 8", "delivered, so seen")
    local played = #H.S.played
    H.advance(3)
    t.eq(#H.S.played, played, "once, not every tick")
    H.chat("/tbx notify motd sound off")
    t.eq(H.config():Find("notify_motd_via").value, "Chat", "the dropdown follows the command")
    H.chat("/tbx notify sound on")
    for _, src in ipairs(Toolbox.Notify.Sources()) do t.eq(Toolbox.Notify.GetSound(src.key), true, src.key) end
    H.chat("/tbx notify via chat")
    t.eq(Toolbox.Notify.GetVia("mail"), "chat")
    H.clearLogs()
    H.chat("/tbx notify sound maybe")
    t.ok(H.logged("sound on|off"))
    H.reload()
    t.eq(Toolbox.Notify.GetSound("mail"), true, "saved")
    t.eq(Toolbox.Notify.GetVia("mail"), "chat")
  end)

  t.test("friends and guild members coming online: chat lines, only while playing, once each", function()
    H.boot()
    H.clearLogs()
    H.callback("ShroudOnFriendStatusChanged",
      { { name = "Alice", online = true }, { name = "Bob", online = false } }, 0)
    t.ok(H.logged("Friends online: Alice came online%."), H.lastLog())
    t.no(H.logged("Bob"), "going offline isn't news")
    H.clearLogs()
    H.advance(3)
    t.no(H.logged("Alice"), "once")
    H.callback("ShroudOnFriendStatusChanged", { { name = "Cara", online = true }, { name = "Dan", online = true } }, 2)
    t.ok(H.logged("Cara, Dan came online%. %(And others the game didn't list%.%)"), H.lastLog())
    H.clearLogs()
    H.callback("ShroudOnGuildMemberStatusChanged", { { name = "Eve", online = true } }, 0)
    t.no(H.logged("Eve"), "guild members: off by default")
    H.chat("/tbx notify guild on")
    H.callback("ShroudOnGuildMemberStatusChanged", { { name = "Finn", online = true } }, 0)
    t.ok(H.logged("Guild members online: Finn came online%."), H.lastLog())
    t.no(H.logged("Eve"), "what came while it was off stays unsaid")
    H.reload()
    H.clearLogs()
    H.callback("ShroudOnFriendStatusChanged", { { name = "Gus", online = true } }, 0)
    t.ok(H.logged("Friends online: Gus came online%."), "after a reload the numbering starts again")
  end)

  t.test("a compact Notifications window: switched with what it shows kept; saved", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    t.eq(H.notify():IsShown(), true)
    H.chat("/tbx config")
    H.change("toolbox_config", "notify_compact", true)
    local w = H.notify()
    t.eq(w.compact, true, "rebuilt compact")
    t.eq(w:IsShown(), true, "still open")
    t.eq(w:Find("n_motd").visible, true, "the notice it showed is still there")
    t.eq(w:Find("n_motd_text").text, "Raid at 8")
    H.reload()
    t.eq(Toolbox.Notify.GetCompact(), true, "saved")
    H.setMotd("Siege tonight")
    t.eq(H.notify().compact, true, "built compact next time")
    H.clearLogs()
    H.chat("/tbx notify compact off")
    t.ok(H.logged("Compact Notifications window: off"))
    t.eq(H.notify().compact, false)
    H.chat("/tbx config")
    t.eq(H.config():Find("notify_compact").value, false, "the checkbox follows")
  end)

  t.test("the Notifications window's text size: the theme's until set, changed in place, saved", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    local w = H.notify()
    t.eq(w:Find("n_motd_text").style.fontSize, nil, "the theme's size")
    t.eq(Toolbox.Notify.GetFont(), Toolbox.Window.FONT_DEFAULT, "what the slider shows")
    H.chat("/tbx config")
    H.change("toolbox_config", "notify_font", 16)
    t.eq(H.notify(), w, "not rebuilt")
    t.eq(w:Find("n_motd_text").style.fontSize, 16)
    t.eq(w:Find("n_motd_title").style.fontSize, 18, "the heading a little larger")
    t.eq(w:Find("n_motd_text").text, "Raid at 8", "what it shows is kept")
    t.eq(H.config():Find("notify_font_value").text, "16")
    t.eq(Toolbox.Notify.SetFont(99), false, "out of range")
    H.reload()
    t.eq(Toolbox.Notify.GetFont(), 16, "saved")
    H.setMotd("Siege tonight")
    t.eq(H.notify():Find("n_motd_text").style.fontSize, 16, "built at that size")
    H.chat("/tbx notify compact on")
    t.eq(H.notify():Find("n_motd_text").style.fontSize, 16, "and when rebuilt compact")
  end)

  t.test("the notification HUD's text size: the XP windows' until set, resized in place, saved", function()
    H.boot()
    H.chat("/tbx notify mail via hud")
    H.setNotes{ unreadMail = 2 }
    local NH = Toolbox.Notify.Hud
    local row = H.nhud():Find("nh_1")
    t.eq(row.style.fontSize, Toolbox.Window.GetFont())
    Toolbox.Window.SetFont(14)
    t.eq(row.style.fontSize, 14, "follows the XP windows while unset")
    local h0 = H.nhud().height
    H.chat("/tbx config")
    H.change("toolbox_config", "nhud_font", 20)
    t.eq(H.nhud():Find("nh_1"), row, "not rebuilt")
    t.eq(row.style.fontSize, 20)
    t.eq(row.style.height, Toolbox.Window.LineHeight(20))
    t.eq(H.nhud():Find("nh_scroll").style.height, Toolbox.Window.LineHeight(20), "its one line")
    t.ok(H.nhud().height > h0, "the strip re-fits")
    Toolbox.Window.SetFont(10)
    t.eq(row.style.fontSize, 20, "its own size now")
    t.eq(H.config():Find("nhud_font_value").text, "20")
    t.eq(NH.SetFont(8), false, "out of range")
    H.reload()
    t.eq(NH.GetFont(), 20, "saved")
    t.eq(H.saved("notify_hud").font, 20)
    t.eq(H.nhud():Find("nh_1").style.fontSize, 20, "built at that size")
  end)

  t.test("the notification HUD's line spacing: the XP windows' until set, in place, saved", function()
    H.boot()
    H.chat("/tbx notify mail via hud")
    H.setNotes{ unreadMail = 2 }
    local NH = Toolbox.Notify.Hud
    local W = Toolbox.Window
    local row = H.nhud():Find("nh_1")
    t.eq(NH.GetSpacing(), W.GetSpacing(), "the XP windows' until set")
    H.chat("/tbx config")
    H.change("toolbox_config", "nhud_spacing", 8)
    t.eq(H.nhud():Find("nh_1"), row, "not rebuilt")
    t.eq(row.style.height, W.LineHeight(NH.GetFont(), 8))
    t.eq(H.nhud():Find("nh_scroll").style.height, W.LineHeight(NH.GetFont(), 8))
    W.SetSpacing(0)
    t.eq(row.style.height, W.LineHeight(NH.GetFont(), 8), "its own now")
    t.eq(H.config():Find("nhud_spacing_value").text, "8")
    t.eq(NH.SetSpacing(40), false, "out of range")
    H.reload()
    t.eq(NH.GetSpacing(), 8, "saved")
  end)

  t.test("the Notifications page says where each notification's sound is picked", function()
    H.boot()
    H.chat("/tbx config")
    local hint = H.config():Find("notify_sound_hint").text
    t.ok(hint:find("on the Sounds page", 1, true), hint)
    t.ok(hint:find("Chime, Ping, Tap, Bell, Low notes", 1, true), "the choices, from the sound list: " .. hint)
  end)

  t.test("a sound per source: picked on the Sounds page or in chat; each distinct sound once", function()
    H.boot()
    for _, f in ipairs({ "notify", "ping", "tap" }) do H.S.files["toolbox/" .. f .. ".ogg"] = true end
    H.reload()
    H.advance(2)
    H.chat("/tbx notify via chat")
    H.chat("/tbx notify friends sound ping")
    H.chat("/tbx notify motd sound tap")
    H.chat("/tbx notify mail sound on")          -- the default chime
    t.eq(Toolbox.Notify.GetSoundKey("friends"), "ping")
    t.eq(Toolbox.Notify.GetSound("friends"), true, "naming a sound turns it on")
    local before = #H.S.played
    H.callback("ShroudOnFriendStatusChanged", { { name = "Alice", online = true } }, 0)
    t.eq(H.S.played[#H.S.played].name, "ping")
    H.setGuild("Knights", "Raid at 8")
    H.setNotes{ unreadMail = 1 }
    H.advance(1)
    local names = {}
    for i = before + 1, #H.S.played do names[#names + 1] = H.S.played[i].name end
    table.sort(names)
    t.eq(table.concat(names, ","), "notify,ping,tap", "each source its own sound")
    before = #H.S.played
    H.callback("ShroudOnFriendStatusChanged", { { name = "Bob", online = true }, { name = "Cara", online = true } }, 0)
    t.eq(#H.S.played - before, 1, "two friends at once: one ping")
    H.chat("/tbx config")
    t.eq(H.config():Find("notify_friends_snd").value, "Ping")
    H.change("toolbox_config", "notify_friends_snd", "Bell")
    t.eq(Toolbox.Notify.GetSoundKey("friends"), "buff_expiring")
    t.eq(H.config():Find("notify_guild_snd").enabled, false, "greyed out while that source has no sound")
    H.clearLogs()
    H.chat("/tbx notify friends sound kazoo")
    t.ok(H.logged("chime, ping, tap, bell, low notes"), H.lastLog())
    H.reload()
    t.eq(Toolbox.Notify.GetSoundKey("friends"), "buff_expiring", "saved")
  end)

  t.test("a refused window is retried and not marked seen", function()
    H.boot()
    H.S.showRefused = true
    H.setGuild("Knights", "Raid at 8")
    H.advance(2)
    t.no(H.notify():IsShown())
    t.eq(seen("motd"), nil, "not seen yet")
    H.S.showRefused = false
    H.advance(1)
    t.ok(H.notify():IsShown())
    t.eq(seen("motd"), "Raid at 8")
  end)

  t.test("each character remembers its own", function()
    H.boot()
    H.setGuild("Knights", "Raid at 8")
    H.advance(1)
    H.closeWindow("toolbox_notify")
    H.S.char.name = "Alt"
    H.advance(1)
    t.ok(H.notice("motd").shown, "new to the alt")
  end)

  t.test("the old guild_motd setting is taken over", function()
    H.boot({ ["character:Tester"] = { guild_motd = { show = false, seen = "Raid at 8" } } })
    t.no(Toolbox.Notify.IsOn("motd"))
    Toolbox.Notify.SetOn("motd", true)
    H.setGuild("Knights", "Raid at 8")
    H.advance(2)
    t.eq(H.notify(), nil, "already seen before the move")
  end)

  t.test("/tbx motd: shows the message any time; on/off; outside a guild says so", function()
    H.boot()
    H.clearLogs()
    H.chat("/tbx motd")
    t.ok(H.logged("not in a guild"))
    H.setGuild("Knights", "")
    H.chat("/tbx motd")
    t.ok(H.logged("no message of the day"))
    H.chat("/tbx motd off")
    t.no(Toolbox.Notify.IsOn("motd"))
    H.setGuild("Knights", "Raid at 8")
    H.advance(2)
    t.eq(H.notify(), nil, "off: nothing by itself")
    H.chat("/tbx motd")
    t.ok(H.notice("motd").shown)
    t.eq(H.notice("motd").text, "Raid at 8")
  end)

  -- mail and the other notices ----------------------------------------------

  t.test("new mail: shown when the count goes up, quiet when it goes down", function()
    settled()
    H.setNotes{ unreadMail = 2 }
    t.eq(H.notice("mail").text, "You have 2 unread letters.")
    t.eq(seen("mail"), 2)
    H.closeWindow("toolbox_notify")
    H.setNotes{ unreadMail = 1 }                 -- read one
    t.no(H.notify():IsShown(), "no notice for fewer")
    t.eq(seen("mail"), 1)
    H.setNotes{ unreadMail = 3 }
    t.eq(H.notice("mail").text, "2 new letters (3 unread in all).")
  end)

  t.test("counts reading 0 while the game loads don't count as read", function()
    H.boot()
    H.setNotes{ unreadMail = 3 }
    H.closeWindow("toolbox_notify")
    H.restart(nil, true)
    H.S.notes.unreadMail = 0                     -- not loaded yet
    H.advance(5)
    H.setNotes{ unreadMail = 3 }                 -- loaded: the same 3
    H.advance(1)
    t.no(H.notify() and H.notify():IsShown(), "nothing new")
  end)

  t.test("flags: mail expiring and new rewards, once each time they come on", function()
    settled()
    H.setNotes{ mailExpiring = true, newRewards = true }
    t.eq(H.notice("expiring").text, "Some of your mail is about to expire. Collect it before it's gone.")
    t.eq(H.notice("rewards").text, "You have new rewards waiting.")
    H.closeWindow("toolbox_notify")
    H.advance(3)
    t.no(H.notify():IsShown())
    H.setNotes{ mailExpiring = false }
    H.setNotes{ mailExpiring = true }
    t.ok(H.notice("expiring").shown, "on again")
    t.no(H.notice("rewards").shown, "only what's new is listed")
  end)

  t.test("ransoms and guild applications; -1 applications means unknown", function()
    settled()
    H.setNotes{ ransoms = 1 }
    t.eq(H.notice("ransoms").text, "You have 1 ransom notice.")
    H.closeWindow("toolbox_notify")
    H.setNotes{ guildApplications = -1 }
    t.no(H.notify():IsShown())
    H.setNotes{ guildApplications = 2 }
    t.eq(H.notice("applications").text, "2 guild applications are waiting.")
  end)

  t.test("several at once share one window", function()
    settled()
    H.setGuild("Knights", "Raid at 8")
    H.S.notes.unreadMail = 1
    H.advance(1)
    t.ok(H.notice("motd").shown)
    t.ok(H.notice("mail").shown)
    t.no(H.notice("ransoms").shown)
  end)

  t.test("a source switched off keeps up quietly, so switching it on brings no old news", function()
    settled()
    H.chat("/tbx notify mail off")
    t.no(Toolbox.Notify.IsOn("mail"))
    H.setNotes{ unreadMail = 4 }
    t.eq(H.notify(), nil)
    t.eq(seen("mail"), 4)
    H.chat("/tbx notify mail on")
    H.advance(2)
    t.eq(H.notify(), nil)
    H.setNotes{ unreadMail = 5 }
    t.eq(H.notice("mail").text, "1 new letter (5 unread in all).")
  end)

  t.test("/tbx notify lists, switches and shows everything current", function()
    settled()
    H.clearLogs()
    H.chat("/tbx notify")
    t.ok(H.logged("motd %(Guild message of the day%) on, mail %(New mail%) on"))
    H.chat("/tbx notify nope on")
    t.ok(H.logged("Use /toolbox notify <name> on|off"))
    H.chat("/tbx notify show")
    t.ok(H.logged("Nothing to show right now"))
    H.setNotes{ unreadMail = 2 }
    H.closeWindow("toolbox_notify")
    H.chat("/tbx notify show")
    t.eq(H.notice("mail").text, "You have 2 unread letters.", "current state, though seen")
  end)

  t.test("settings: one toggle per source, following the commands", function()
    H.boot()
    H.chat("/tbx config")
    for _, src in ipairs(Toolbox.Notify.Sources()) do
      t.eq(H.config():Find("notify_" .. src.key).value, src.default ~= false,
        src.key .. " on by default, but guild (and skill level ups)")
    end
    H.chat("/tbx notify rewards off")
    t.eq(H.config():Find("notify_rewards").value, false)
    H.change("toolbox_config", "notify_mail", false)
    t.no(Toolbox.Notify.IsOn("mail"))
    t.eq(H.saved("notify").sources.mail.on, false)
    t.eq(H.saved("notify").sources.mail.via, "window", "delivered by window (the only way for now)")
  end)

  -- the notification HUD --------------------------------------------------

  -- Settled, with mail going to the HUD.
  local function mailToHud()
    settled()
    H.chat("/tbx notify mail via hud")
  end

  t.test("the HUD stays hidden until a source uses it", function()
    settled()
    t.eq(H.nhud().visible, false)
    H.chat("/tbx config")
    H.advance(1)
    t.eq(H.nhud().visible, false, "not even in settings when nothing goes there")
  end)

  t.test("via hud: newest on top, one line each, the whole notice on hover", function()
    mailToHud()
    t.eq(Toolbox.Notify.GetVia("mail"), "hud")
    t.eq(H.saved("notify").sources.mail.via, "hud")
    H.setNotes{ unreadMail = 2 }
    t.ok(H.nhud().visible ~= false, "shown")
    t.eq(H.notify(), nil, "no window")
    local text, tip = H.nhudRow(1)
    t.ok(text:find("New mail: You have 2 unread letters%.$"), text)
    t.ok(tip:find("^New mail.*\nYou have 2 unread letters%.$"), tip)
    H.setNotes{ unreadMail = 3 }
    t.ok(H.nhudRow(1):find("1 new letter"), "newest on top")
    t.ok(H.nhudRow(2):find("2 unread letters"))
    t.eq(H.nhudRow(3), nil)
    local row = H.nhud():Find("nh_1")
    t.eq(row.style.whiteSpace, "nowrap", "one line (the label ends in ... when it runs out of room)")
  end)

  t.test("the HUD hides after 10 seconds, but not while hovered", function()
    mailToHud()
    t.eq(Toolbox.Notify.Hud.GetHideAfter(), 10)
    H.setNotes{ unreadMail = 1 }
    H.advance(5)
    t.ok(H.nhud().visible ~= false)
    H.nhudHover(true)
    H.advance(20)
    t.ok(H.nhud().visible ~= false, "kept while the pointer is on it")
    H.nhudHover(false)
    H.advance(11)
    t.eq(H.nhud().visible, false, "hidden after the wait")
    H.setNotes{ unreadMail = 2 }
    t.ok(H.nhud().visible ~= false, "back for the next one")
    t.ok(H.nhudRow(1):find("1 new letter"), H.nhudRow(1))
    t.ok(H.nhudRow(2):find("1 unread letter"), "the one before is kept, to look back")
    local classes = function(i) return H.nhud():Find("nh_" .. i):Classes() end
    t.ok(classes(1).bright and not classes(1).dim, "the new one stands out")
    t.ok(classes(2).dim and not classes(2).bright, "the one shown before is dimmed")
  end)

  t.test("hide after: never, other choices, and chat", function()
    mailToHud()
    H.chat("/tbx notify hud hide never")
    H.setNotes{ unreadMail = 1 }
    H.advance(120)
    t.ok(H.nhud().visible ~= false, "never hidden")
    H.clearLogs()
    H.chat("/tbx notify hud hide 7")
    t.ok(H.logged("seconds: 5, 10, 20, 30, 60"))
    H.chat("/tbx notify hud hide 30")
    t.eq(H.saved("notify_hud").hideAfter, 30)
  end)

  t.test("the HUD keeps the latest 20 across a reload; clear empties it", function()
    mailToHud()
    for n = 1, 25 do H.setNotes{ unreadMail = n } end
    t.ok(H.nhudRow(20) ~= nil)
    t.eq(#H.saved("notify_history").list, Toolbox.Notify.Hud.KEEP)
    H.reload()
    t.ok(H.nhudRow(1):find("25 unread in all"), "kept, newest on top")
    H.chat("/tbx notify hud clear")
    t.eq(H.nhudRow(1), nil)
    t.eq(H.nhud().visible, false)
  end)

  t.test("after a reload every notice is old; hide after never: new for 10 seconds", function()
    mailToHud()
    H.setNotes{ unreadMail = 1 }
    H.reload()
    H.setNotes{ unreadMail = 2 }
    local classes = function(i) return H.nhud():Find("nh_" .. i):Classes() end
    t.ok(classes(1).bright, "just arrived")
    t.ok(classes(2).dim, "from before the reload")
    t.eq(H.saved("notify_history").list[1].fresh, nil, "saved without it")
    H.chat("/tbx notify hud hide never")
    H.setNotes{ unreadMail = 3 }
    t.ok(classes(1).bright)
    H.advance(Toolbox.Notify.Hud.HIDE_DEFAULT + 1)
    t.ok(classes(1).dim, "old after 10 seconds, though the HUD stays")
    t.ok(H.nhud().visible ~= false)
  end)

  t.test("another character: its own HUD list and settings, nothing carried over", function()
    mailToHud()
    H.setNotes{ unreadMail = 2 }
    H.chat("/tbx notify hud hide never")
    Toolbox.Notify.Hud.SetFont(18)
    t.ok(H.nhudRow(1):find("2 unread letters"), "Tester's notice")
    H.setNotes{ unreadMail = 0 }                  -- (the harness's mail count is shared: nothing new for Alt)
    H.S.char.name = "Alt"                         -- logs in as another character, no reload
    H.chat("/tbx notify mail via hud")
    H.advance(1)
    t.eq(H.nhudRow(1), nil, "none of Tester's rows on Alt's HUD")
    t.eq(Toolbox.Notify.Hud.GetHideAfter(), Toolbox.Notify.Hud.HIDE_DEFAULT, "Alt's own settings")
    t.eq(Toolbox.Notify.Hud.GetFont(), Toolbox.Window.GetFont())
    H.setNotes{ unreadMail = 5 }
    H.advance(1)
    t.ok(H.nhudRow(1):find("5 unread letters"), "Alt's own notice: " .. tostring(H.nhudRow(1)))
    t.eq(H.nhudRow(2), nil, "and only that")
    local alt = H.saved("notify_history").list
    t.eq(#alt, 1, "Alt's saved history has only Alt's")
    H.S.char.name = "Tester"
    H.advance(1)
    -- (the shared count of 5 is new to Tester too: its own notice on top of its old one)
    t.ok(H.nhudRow(2):find("2 unread letters"), "back to Tester: Tester's list again")
    t.eq(H.nhudRow(3), nil, "none of Alt's")
    t.eq(Toolbox.Notify.Hud.GetHideAfter(), 0, "and settings")
    t.eq(Toolbox.Notify.Hud.GetFont(), 18)
    t.eq(#H.saved("notify_history").list, 2, "Tester's history: Tester's two")
  end)

  t.test("another character with settings open: the controls show its values", function()
    mailToHud()
    H.chat("/tbx notify hud hide never")
    Toolbox.Notify.Hud.SetFont(18)
    H.chat("/tbx notify rewards off")
    H.chat("/tbx config")
    H.change("toolbox_config", "category", "Notifications")
    local w = H.configRaw()
    t.eq(w:Find("nhud_hide").value, "Never")
    H.S.char.name = "Alt"
    H.advance(2)
    t.eq(w:Find("nhud_hide").value, "10 seconds", "Alt's hide delay")
    t.eq(w:Find("nhud_font").value, Toolbox.Window.GetFont(), "Alt's text size")
    t.eq(w:Find("notify_rewards").value, true, "Alt's sources")
    t.eq(w:Find("notify_mail_via").value, "Window", "Alt's delivery")
    H.S.char.name = "Tester"
    H.advance(2)
    t.eq(w:Find("nhud_hide").value, "Never", "and Tester's again")
    t.eq(w:Find("nhud_font").value, 18)
    t.eq(w:Find("notify_rewards").value, false)
  end)

  t.test("another character with no HUD position of its own: the HUD stays where it is", function()
    mailToHud()
    H.setNotes{ unreadMail = 2 }
    local function drag(x, y) H.S.frames.toolbox_notify_hud.x, H.S.frames.toolbox_notify_hud.y = x, y end
    drag(600, 450)                                -- Tester places it by its grip
    H.advance(1)
    t.eq(H.saved("notify_hud").x, 600, "Tester's place saved")
    H.setNotes{ unreadMail = 0 }
    H.S.char.name = "Alt"                         -- a character (or account) that never moved it
    H.chat("/tbx notify mail via hud")
    H.chat("/tbx config")                         -- shown, to see where it is
    H.advance(2)
    local x, y = Toolbox.Notify.Hud.GetPosition()
    t.eq(x, 600, "not back in the top-left corner")
    t.eq(y, 450)
    t.eq(H.saved("notify_hud").x, 600, "and now Alt's place too")
    drag(300, 200)                                -- Alt moves it
    H.advance(1)
    H.S.char.name = "Tester"
    H.advance(1)
    x, y = Toolbox.Notify.Hud.GetPosition()
    t.eq(x, 600, "back to Tester: Tester's own place")
  end)

  t.test("the HUD shows while settings are open, to place it", function()
    mailToHud()
    H.chat("/tbx config")
    H.advance(1)
    t.ok(H.nhud().visible ~= false)
    t.eq(H.config():Find("notify_mail_via").value, "HUD")
    t.eq(H.config():Find("nhud_hide").value, "10 seconds")
    H.change("toolbox_config", "notify_rewards_via", "HUD")
    t.eq(Toolbox.Notify.GetVia("rewards"), "hud")
    H.change("toolbox_config", "nhud_hide", "1 minute")
    t.eq(Toolbox.Notify.Hud.GetHideAfter(), 60)
    H.closeWindow("toolbox_config")
    H.advance(1)
    t.eq(H.nhud().visible, false)
  end)

  t.test("/tbx notify via hud sends everything there; per source too", function()
    settled()
    H.chat("/tbx notify via hud")
    for _, src in ipairs(Toolbox.Notify.Sources()) do t.eq(Toolbox.Notify.GetVia(src.key), "hud", src.key) end
    H.chat("/tbx notify motd via window")
    t.eq(Toolbox.Notify.GetVia("motd"), "window")
    H.clearLogs()
    H.chat("/tbx notify via sky")
    t.ok(H.logged("via window|hud"))
    H.setGuild("Knights", "Raid at 8")
    H.S.notes.unreadMail = 1
    H.advance(1)
    t.ok(H.notice("motd").shown, "the guild message in the window")
    t.no(H.notice("mail") and H.notice("mail").shown, "mail not in the window")
    t.ok(H.nhudRow(1):find("New mail"), "mail on the HUD")
  end)

  t.test("a long guild message works (MoonSharp: pattern too complex)", function()
    H.boot()
    local long = "  Welcome! " .. string.rep("Raid tonight at 8, bring potions. ", 10) .. "\n"
    H.setGuild("Knights", long)
    H.advance(1)
    t.eq(H.notice("motd").text, Toolbox.Trim(long))
  end)

  t.test("the HUD in settings: an empty-state line; lines leave room for the scrollbar", function()
    settled()
    H.chat("/tbx notify mail via hud")
    H.chat("/tbx config")
    H.advance(1)
    local hud = H.nhud()
    t.ok(hud.visible ~= false)
    t.ok(hud:Find("nh_empty").visible ~= false, "the empty-state line")
    t.eq(hud:Find("nh_empty").text, Toolbox.Notify.Hud.EMPTY_TEXT)
    t.eq(hud:Find("nh_scroll").visible, false, "no empty scroll area")
    H.setNotes{ unreadMail = 1 }
    t.eq(hud:Find("nh_empty").visible, false)
    t.ok(hud:Find("nh_scroll").visible ~= false)
    local NH = Toolbox.Notify.Hud
    t.eq(hud:Find("nh_1").style.width, NH.WIDTH - NH.SCROLLBAR, "narrower than the scroll area")
  end)
end
