-- Setups (Toolbox.Backup): a character's settings and positions copied through the account file, so another
-- character on the same computer (someone else's too) can import them. Copies, never linked.
local H = require("harness")

return function(t)
  local B = function() return Toolbox.Backup end
  local function switchTo(name)
    H.callback("ShroudOnLogOut")
    H.S.char.name = name
    H.callback("ShroudOnSceneLoaded", "Novia")
    H.advance(1)
  end
  local function names()
    local out = {}
    for _, s in ipairs(B().Setups()) do out[#out + 1] = s.label end
    return table.concat(out, ", ")
  end
  -- "Mom" sets up her Toolbelt and plays a while (her copy is kept at the next flush).
  local function momPlays()
    H.boot()
    H.S.char.name = "Mom"
    H.reload()
    H.chat("/tbx settings share on")            -- she lists hers for the others
    H.chat("/tbx buffs")
    Toolbox.BuffBar.SetSize(30)
    H.chat("/tbx vitals")
    H.S.frames.toolbox_buffs.x, H.S.frames.toolbox_buffs.y = 640, 480
    H.advance(Toolbox.flushSeconds or 31)
    H.advance(31)
  end

  t.test("every character's setup is kept for the others as it plays; not its own in its list", function()
    momPlays()
    t.eq(names(), "", "Mom doesn't see her own")
    switchTo("Dad")
    t.ok(names():find("^Mom %(character"), names())
  end)

  t.test("Dad imports Mom's: her settings and places, at once; later changes stay apart", function()
    momPlays()
    switchTo("Dad")
    t.no(Toolbox.BuffBar.IsEnabled(), "Dad's own setup first")
    H.clearLogs()
    H.chat("/tbx settings import Mom")
    t.ok(H.logged("Imported 'Mom'"), H.lastLog())
    t.ok(Toolbox.BuffBar.IsEnabled(), "her buff bar")
    t.eq(Toolbox.BuffBar.GetSize(), 30)
    t.ok(Toolbox.Vitals.IsShown and Toolbox.Vitals.IsShown() or H.vitals(), "her health bars")
    t.eq(H.S.frames.toolbox_buffs.x, 640, "where she keeps it")
    Toolbox.BuffBar.SetSize(44)
    switchTo("Mom")
    t.eq(Toolbox.BuffBar.GetSize(), 30, "Mom's untouched by Dad's change")
  end)

  t.test("export under a name; import it from another character; delete it", function()
    momPlays()
    H.clearLogs()
    H.chat("/tbx settings export Raid layout")
    t.ok(H.logged("Exported your settings and positions as 'Raid layout'"), H.lastLog())
    Toolbox.BuffBar.SetSize(22)                 -- changes after the export aren't in it
    switchTo("Kid")
    t.ok(names():find("^Raid layout, Mom"), "named ones first: " .. names())
    H.chat("/tbx settings import raid layout")
    t.eq(Toolbox.BuffBar.GetSize(), 30, "as it was exported")
    H.chat("/tbx settings delete Raid layout")
    t.no(names():find("Raid layout"), names())
    H.clearLogs()
    H.chat("/tbx settings import Nobody")
    t.ok(H.logged("No setup called 'Nobody'"), H.lastLog())
  end)

  t.test("an import keeps what this character was told: notices aren't shown again", function()
    momPlays()
    switchTo("Dad")
    H.setGuild("Knights", "Raid at 8")
    H.advance(3)
    local seen = H.saved("notify").sources.motd.seen
    t.eq(seen, "Raid at 8")
    H.chat("/tbx settings import Mom")
    H.advance(3)
    t.eq(H.saved("notify").sources.motd.seen, "Raid at 8", "Dad's own")
  end)

  t.test("the settings page: pick, Import (second click), Export, Delete", function()
    momPlays()
    switchTo("Dad")
    H.chat("/tbx config")
    local w = H.config()
    local pick = w:Find("setup_pick")
    t.ok(pick.value:find("^Mom"), tostring(pick.value))
    H.click("toolbox_config", "setup_import")
    t.no(Toolbox.BuffBar.IsEnabled(), "the first click only asks")
    t.eq(w:Find("setup_import").text, "Click again to confirm")
    H.click("toolbox_config", "setup_import")
    t.ok(Toolbox.BuffBar.IsEnabled(), "imported")
    t.ok(w:Find("setup_msg").text:find("Imported 'Mom'"), w:Find("setup_msg").text)
    H.submit("toolbox_config", "setup_name", "Dad's")
    t.ok(names():find("Dad's"), names())
    H.change("toolbox_config", "setup_pick", "Dad's")
    H.click("toolbox_config", "setup_delete")
    H.click("toolbox_config", "setup_delete")
    t.no(names():find("Dad's"), names())
  end)

  t.test("listing is off by default, each character's own choice, and off takes its copy away", function()
    H.boot()
    H.chat("/tbx buffs")
    H.advance(40)
    t.eq(Toolbox.Backup.GetShare(), false)
    switchTo("Alt")
    t.eq(names(), "", "Tester didn't list its setup")
    switchTo("Tester")
    H.chat("/tbx config")
    H.change("toolbox_config", "setup_share", true)
    switchTo("Alt")
    t.ok(names():find("^Tester %(character"), names())
    t.eq(Toolbox.Backup.GetShare(), false, "Alt's own choice: still off")
    H.chat("/tbx settings import Tester")
    t.eq(Toolbox.Backup.GetShare(), false, "an import doesn't bring the choice with it")
    H.advance(40)
    switchTo("Tester")
    t.eq(Toolbox.Backup.GetShare(), true)
    H.clearLogs()
    H.chat("/tbx settings share off")
    t.ok(H.logged("isn't listed for others"), H.lastLog())
    switchTo("Alt")
    t.eq(names(), "", "its copy is gone")
  end)

  t.test("names are cleaned: no slashes, trimmed, not too long", function()
    H.boot()
    t.eq(B().CleanName("  a/b\\c  "), "a b c")
    t.eq(B().CleanName("   "), nil)
    t.eq(#B().CleanName(string.rep("x", 60)), B().NAME_MAX)
  end)

  -- Review 2026-10-04 (11): a refused write changes nothing and isn't reported as done.
  t.test("an import the game refuses to store changes nothing and says so", function()
    momPlays()
    H.chat("/tbx settings export A")
    switchTo("Dad")
    H.chat("/tbx buffs")
    Toolbox.BuffBar.SetSize(40)
    H.S.saveRefused = true
    H.clearLogs()
    H.chat("/tbx settings import A")
    t.ok(H.logged("Couldn't import"), H.lastLog())
    H.S.saveRefused = false
    t.ok(Toolbox.BuffBar.IsEnabled(), "Dad's bar still on")
    t.eq(Toolbox.BuffBar.GetSize(), 40, "at Dad's size")
    t.eq(H.saved("buffbar").size, 40, "and saved so")
  end)

  t.test("a refused export, delete or shared copy isn't reported as done; the copy is tried again", function()
    momPlays()
    Toolbox.BuffBar.SetSize(26)                  -- Mom's copy is now behind...
    H.S.saveRefused = true                       -- ...and the game won't store it
    H.clearLogs()
    H.chat("/tbx settings export B")
    t.ok(H.logged("Couldn't export"), H.lastLog())
    H.advance(62)
    t.eq(Toolbox.setupDirty, true, "still to do")
    H.S.saveRefused = false
    H.advance(62)
    switchTo("Dad")
    t.no(names():find("^B"), "no half-made export: " .. names())
    H.chat("/tbx settings import Mom")
    t.eq(Toolbox.BuffBar.GetSize(), 26, "the copy caught up once the game took it")
  end)

  -- Review 2026-10-04 (12): the second click must be on the same setup.
  t.test("Import and Delete: a second click on another setup only asks again", function()
    momPlays()
    H.chat("/tbx settings export A")
    Toolbox.BuffBar.SetSize(40)
    H.chat("/tbx settings export B")
    switchTo("Dad")
    H.chat("/tbx config")
    H.change("toolbox_config", "setup_pick", "A")
    H.click("toolbox_config", "setup_import")
    H.change("toolbox_config", "setup_pick", "B")
    H.click("toolbox_config", "setup_import")
    t.no(Toolbox.BuffBar.IsEnabled(), "B not imported on one click")
    H.click("toolbox_config", "setup_import")
    t.eq(Toolbox.BuffBar.GetSize(), 40, "B on its own second click")
    H.change("toolbox_config", "setup_pick", "A")
    H.click("toolbox_config", "setup_delete")
    H.change("toolbox_config", "setup_pick", "B")
    H.click("toolbox_config", "setup_delete")
    t.ok(names():find("B"), "B not deleted on one click: " .. names())
  end)

  -- Review 2026-10-07 (12): the armed button belongs to the character that clicked it.
  t.test("Import and Delete: a click after a character switch only asks again", function()
    momPlays()
    H.chat("/tbx settings export A")
    H.chat("/tbx config")
    for _, button in ipairs({ "setup_import", "setup_delete" }) do
      switchTo("Dad")
      H.change("toolbox_config", "setup_pick", "A")
      H.click("toolbox_config", button)          -- Dad arms it...
      switchTo("Kid")                            -- ...and Kid, Settings still open, clicks once
      t.eq(H.config():Find(button).text, button == "setup_import" and "Import" or "Delete", "disarmed")
      H.change("toolbox_config", "setup_pick", "A")
      H.click("toolbox_config", button)
      t.no(Toolbox.BuffBar.IsEnabled(), button .. ": nothing imported on Kid's one click")
      t.ok(names():find("A"), button .. ": nothing deleted on Kid's one click: " .. names())
    end
  end)

  -- Review 2026-10-07 (16): sharing on or off is only reported once the game stored it.
  t.test("share on/off: a refused write isn't reported as done and changes nothing", function()
    momPlays()
    H.chat("/tbx settings share off")
    H.S.saveRefused = true
    H.clearLogs()
    H.chat("/tbx settings share on")
    t.ok(H.logged("Couldn't list your setup"), H.lastLog())
    t.eq(B().GetShare(), false, "still off")
    H.S.saveRefused = false
    switchTo("Dad")
    t.eq(names(), "", "nothing listed")
    switchTo("Mom")
    H.chat("/tbx settings share on")
    t.eq(B().GetShare(), true)
    H.S.saveRefused = true
    H.clearLogs()
    H.chat("/tbx settings share off")
    t.ok(H.logged("Couldn't take your setup off the list"), H.lastLog())
    t.eq(B().GetShare(), true, "still on, and so its copy stays")
    H.S.saveRefused = false
    switchTo("Dad")
    t.ok(names():find("^Mom %(character"), names())
  end)

  t.test("share off: a list the game won't change keeps sharing on; a refused choice puts the copy back", function()
    momPlays()
    H.S.refuseKeys = { setups = true }           -- the account's list of setups can't change
    H.clearLogs()
    H.chat("/tbx settings share off")
    t.ok(H.logged("Couldn't take your setup off the list"), H.lastLog())
    t.eq(B().GetShare(), true, "still on, as its copy is still listed")
    t.eq(H.saved("setup_share"), true)
    H.S.refuseKeys = { setup_share = true }      -- now the choice can't be stored
    H.clearLogs()
    H.chat("/tbx settings share off")
    t.ok(H.logged("Couldn't take your setup off the list"), H.lastLog())
    t.eq(B().GetShare(), true)
    H.S.refuseKeys = nil
    switchTo("Dad")
    t.ok(names():find("^Mom %(character"), "its copy put back: " .. names())
    switchTo("Mom")
    H.chat("/tbx settings share off")
    switchTo("Dad")
    t.eq(names(), "", "off once the game takes it")
  end)

  t.test("share on: listed from its first setting; at the setup limit refused and said", function()
    H.boot()
    H.S.char.name = "Fresh"
    H.reload()
    t.eq(B().SetShare(true), true, "the choice is kept, settings or not")
    H.chat("/tbx buffs")
    H.advance(40)
    switchTo("Dad")
    t.ok(names():find("^Fresh %(character"), names())
    for i = 1, B().SETUP_MAX - 1 do H.chat("/tbx settings export N" .. i) end
    switchTo("Full")
    H.chat("/tbx buffs")
    local ok, why = B().SetShare(false)
    t.ok(ok, tostring(why))
    ok, why = B().SetShare(true)
    t.eq(ok, false)
    t.ok(tostring(why):find("already"), tostring(why))
    t.eq(B().GetShare(), false)
  end)

  -- Review 2026-10-04 (13): reset turns sharing off, so the copy goes too.
  t.test("a reset takes the character's shared copy off the list", function()
    momPlays()
    H.chat("/tbx settings reset")
    H.callback("ShroudOnDisableScript")
    H.reload()
    t.eq(Toolbox.Backup.GetShare(), false)
    switchTo("Dad")
    t.eq(names(), "", "Mom's old copy is gone")
  end)
end
