-- Gluing the health & focus bars to the buff bar: one HUD strip.
local H = require("harness")

return function(t)
  local Hud = function() return Toolbox.Hud end

  local function gluedWithBoth()
    H.boot()
    H.chat("/tbx buffs")
    H.chat("/tbx vitals")
    H.chat("/tbx vitals glue on")
    H.advance(1)
  end

  t.test("unglued: two strips, as before", function()
    H.boot()
    H.chat("/tbx buffs")
    H.chat("/tbx vitals")
    t.ok(H.frame() and H.vitals(), "two strips")
    t.eq(H.hud(), nil)
  end)

  t.test("glued: one strip, health & focus on the left, buffs on the right", function()
    gluedWithBoth()
    t.eq(H.frame(), nil, "the buff strip is gone")
    t.eq(H.vitals(), nil, "the vitals strip is gone")
    local hud = H.hud()
    t.ok(hud and hud.visible, "one shared strip")
    local parts = hud.children[1].children
    t.eq(parts[1].id, "vitals", "health & focus first")
    t.eq(parts[2].id, "buffbar", "then the buffs")
    t.eq(hud.children[1].style.paddingLeft, Toolbox.Window.GRIP, "clear of the grip")
    local vw, vh = Toolbox.Vitals.ContentSize()
    local bw, bh = Toolbox.BuffBar.ContentSize()
    t.eq(hud.width, Toolbox.Window.GRIP + vw + Hud().GAP + bw + Hud().PAD)
    t.eq(hud.height, math.max(vh, bh) + Hud().PAD)
    t.eq(parts[2].style.marginLeft, Hud().GAP)
  end)

  t.test("glued strip grows with buffs and fits whichever parts are shown", function()
    gluedWithBoth()
    local w0 = H.hud().width
    H.addBuffs({ { name = "A", remaining = 60, icon = 1 }, { name = "B", remaining = 60, icon = 2 } })
    H.advance(0.5, 0.5)
    t.ok(H.hud().width > w0, "wider with more buffs")
    t.eq(#H.slots("buffs"), 2, "icons still fill in")
    H.chat("/tbx vitals")                              -- hide health & focus
    local bw = Toolbox.BuffBar.ContentSize()
    t.eq(H.hud().width, Toolbox.Window.GRIP + bw + Hud().PAD, "buffs only")
    t.eq(H.hud().children[1].children[1].visible, false)
    t.eq(H.hud().children[1].children[2].style.marginLeft, 0, "no gap before the first shown part")
    H.chat("/tbx buffs")                               -- hide buffs too
    t.eq(H.hud().visible, false, "nothing shown: the strip hides")
    H.chat("/tbx vitals")
    t.eq(H.hud().visible, true)
  end)

  t.test("either section's move commands and buttons move the whole HUD", function()
    gluedWithBoth()
    H.chat("/tbx buffs move 500 60")
    t.eq(H.hud().x, 500)
    H.chat("/tbx vitals move 300 70")
    t.eq(H.hud().x, 300)
    t.eq(H.hud().y, 70)
    H.chat("/tbx config")
    H.click("toolbox_config", "buff_right")
    t.eq(H.hud().x, 310)
    H.click("toolbox_config", "vitals_reset")
    t.eq(H.hud().x, Hud().GLUED_HOME[1])
  end)

  t.test("the glued position is remembered; each strip keeps its own when unglued", function()
    H.boot()
    H.chat("/tbx buffs")
    H.chat("/tbx vitals")
    H.chat("/tbx buffs move 900 40")
    H.chat("/tbx vitals move 100 500")
    H.advance(1)
    H.chat("/tbx vitals glue on")
    H.chat("/tbx buffs move 640 200")
    H.advance(1)
    H.reload()
    t.eq(Hud().IsGlued(), true, "glue remembered")
    t.eq(H.hud().x, 640)
    t.eq(H.hud().y, 200)
    H.chat("/tbx vitals glue off")
    t.eq(H.hud(), nil)
    t.eq(H.frame().x, 900, "the buff bar back where it was")
    t.eq(H.vitals().x, 100, "the vitals too")
    t.eq(H.vitals().y, 500)
  end)

  t.test("glued: sweeps, alerts, flashing and resizing still work", function()
    gluedWithBoth()
    H.S.files["toolbox_buff_expiring.ogg"] = true
    H.reload()
    H.advance(5)
    H.chat("/tbx buffalert 5")
    H.addBuffs({ { name = "Ward", remaining = 12, icon = 9 } })
    H.advance(8, 0.5)
    t.eq(H.playedNames(), "toolbox_buff_expiring")
    t.eq(H.slots("buffs")[1].children[2].visible, true, "the sweep shows")
    local w = H.hud().width
    H.chat("/tbx vitals size 200")
    t.ok(H.hud().width > w, "a bigger vitals part widens the shared strip")
    H.chat("/tbx vitals flash test")
    local seen = {}
    for _ = 1, 10 do
      H.advance(0.2, 0.2)
      seen[H.hud():Find("health_bar").color] = true
    end
    t.ok(seen[Toolbox.Vitals.FLASH_COLOR], "flashes inside the shared strip")
  end)

  t.test("settings checkbox and chat for glue", function()
    H.boot()
    H.chat("/tbx config")
    H.change("toolbox_config", "vitals_glue", true)
    t.eq(Hud().IsGlued(), true)
    H.clearLogs()
    H.chat("/tbx vitals glue")
    t.ok(H.logged("glued to the buff bar"))
    H.chat("/tbx vitals glue off")
    t.eq(H.config():Find("vitals_glue").value, false, "checkbox follows the command")
    H.clearLogs()
    H.chat("/tbx vitals glue maybe")
    t.ok(H.logged("glue on|off"))
  end)

  t.test("a strip that fails to build is reported and doesn't stop the others", function()
    H.boot()
    H.chat("/tbx buffs")
    H.chat("/tbx vitals")
    H.chat("/tbx combat")
    local real = Toolbox.Combat.BuildContent
    Toolbox.Combat.BuildContent = function() error("boom") end
    H.clearLogs()
    H.call(Toolbox.Hud.Build)                          -- as from a callback
    Toolbox.Combat.BuildContent = real
    t.ok(H.logged("Couldn't build the combat HUD: .*boom"), H.lastLog())
    t.eq(H.frame().visible, true, "the buff bar still shows")
    t.eq(H.vitals().visible, true, "the vitals still show")
    H.clearLogs()
    H.chat("/tbx combat debug")
    t.ok(H.logged("combat: shown setting true; build error: .*boom; content missing; no strip"), H.lastLog())
  end)

  t.test("/tbx combat debug describes a working strip", function()
    H.boot()
    H.chat("/tbx combat")
    H.clearLogs()
    H.chat("/tbx combat debug")
    t.ok(H.logged("^combat: shown setting true; content built; strip own, visible true, size %d+ x %d+, at 40, 380"),
      H.lastLog())
  end)
end
