-- Combat stats HUD.
local H = require("harness")

return function(t)
  local C = function() return Toolbox.Combat end
  local function hit(amount, kind) return { kind = kind or "hit", fromYou = true, amount = amount } end
  local function hurt(amount, kind) return { kind = kind or "hit", toYou = true, amount = amount or 0 } end

  -- model -------------------------------------------------------------------

  t.test("model: damage out / taken / healing, crits and avoids", function()
    H.boot()
    local f = C().NewFight(0)
    C().Add(f, hit(100), 1, true)
    C().Add(f, hit(300, "critical"), 2, true)
    C().Add(f, { kind = "hit", fromYourPet = true, amount = 50 }, 2, true)
    C().Add(f, { kind = "hit", fromYourPet = true, amount = 50 }, 2, false)   -- pet not counted
    C().Add(f, hurt(80), 3, true)
    C().Add(f, hurt(0, "dodge"), 3, true)
    C().Add(f, hurt(0, "parry"), 3, true)
    C().Add(f, { kind = "heal", fromYou = true, amount = 120 }, 4, true)
    C().Add(f, { kind = "hit", party = true, amount = 999 }, 4, true)           -- a party member's
    C().Add(f, { kind = "fall", fromYou = true, toYou = true, amount = 30 }, 4, true)
    t.eq(f.out, 450)
    t.eq(f.taken, 80)
    t.eq(f.healed, 120)
    t.eq(f.hits, 3)
    t.near(C().CritPct(f), 100 / 3)
    t.near(C().AvoidPct(f), 200 / 3)
  end)

  t.test("model: 'now' rates use the last few seconds, averages the whole fight", function()
    H.boot()
    local f = C().NewFight(0)
    for s = 0, 9 do C().Add(f, hit(100), s, true) end     -- 100/s for 10 s
    local now, avg = C().Rates(f, 10)
    t.near(now.out, 400 / C().WINDOW)                      -- t = 6..9 are within 5 s of t = 10
    t.near(avg.out, 100)
    now, avg = C().Rates(f, 15)                           -- 5 quiet seconds
    t.near(now.out, 0)
    t.near(avg.out, 1000 / 15)
    t.eq(C().CritPct(C().NewFight(0)), nil, "no hits, no crit %")
  end)

  -- live --------------------------------------------------------------------

  t.test("hidden by default; /tbx combat shows its rows", function()
    H.boot()
    t.eq(H.combatHud().visible, false)
    H.chat("/tbx combat")
    t.eq(H.combatHud().visible, true)
    local rows = H.combatRows()
    t.eq(rows[1], "Fight=--")
    t.eq(rows[2], "DPS=0  avg 0")
    t.eq(rows[7], "MagicResistance=n/a", "the default stat, unreadable here")
  end)

  t.test("a fight: timer, DPS, taken, crit and avoided from combat lines", function()
    H.boot()
    H.S.stats = { { name = "MagicResistance", value = 42 } }
    H.chat("/tbx combat")
    H.setCombat(true)
    for _ = 1, 10 do
      H.combat({ hit(200), hurt(50) })
      H.advance(1)
    end
    H.combat({ hit(400, "critical"), hurt(0, "dodge") })
    H.advance(0.5, 0.5)
    local rows = H.combatRows()
    t.eq(rows[1], "Fight=10s")
    t.ok(rows[2]:find("^DPS=%d"), rows[2])
    t.ok(rows[2]:find("avg 2%d%d$"), rows[2])
    t.eq(rows[5], "Crit=9%")
    t.eq(rows[6], "Avoided=9%")
    t.eq(rows[7], "MagicResistance=42")
    H.setCombat(false)
    H.advance(5)
    rows = H.combatRows()
    t.ok(rows[1]:find("%(ended%)$"), rows[1])
    t.eq(rows[2]:sub(1, 6), "DPS=0 ", "no 'now' damage after the fight")
    t.ok(rows[2]:find("avg 2%d%d$"), "the average stays up: " .. rows[2])
  end)

  t.test("a new fight starts fresh; reset clears", function()
    H.boot()
    H.chat("/tbx combat")
    H.setCombat(true)
    H.combat({ hit(1000) })
    H.advance(2)
    H.setCombat(false)
    H.advance(2)
    H.setCombat(true)
    H.advance(1)
    t.ok(H.combatRows()[2]:find("avg 0$"), "fresh fight")
    H.combat({ hit(500) })
    H.chat("/tbx combat reset")
    t.ok(H.combatRows()[2]:find("avg 0$"), "reset")
  end)

  t.test("damage lines start a fight without combat mode; quiet time ends it", function()
    H.boot()
    H.chat("/tbx combat")
    H.combat({ hit(100) })
    H.advance(1)
    t.no(H.combatRows()[1]:find("ended"))
    H.advance(C().IDLE_END + 1)
    t.ok(H.combatRows()[1]:find("ended"))
  end)

  t.test("pet damage toggle", function()
    H.boot()
    H.chat("/tbx combat")
    H.setCombat(true)
    H.combat({ { kind = "hit", fromYourPet = true, amount = 500 } })
    H.chat("/tbx combat pet off")
    H.combat({ { kind = "hit", fromYourPet = true, amount = 500 } })
    H.advance(1)
    t.ok(H.combatRows()[2]:find("avg 500$"), "only the first counted: " .. H.combatRows()[2])
    t.eq(C().GetPet(), false)
  end)

  t.test("stats: add readable ones by name, refuse unknown / hidden / duplicates, remove", function()
    H.boot()
    H.S.stats = { { name = "MagicResistance", value = 42 }, { name = "Resist", value = 12.5 },
                  { name = "Secret", value = 1, hidden = true } }
    H.chat("/tbx combat")
    H.clearLogs()
    H.chat("/tbx combat stat add Resist")
    t.ok(H.logged("Added Resist"))
    H.advance(0.5, 0.5)
    t.eq(H.combatRows()[8], "Resist=12.5")
    H.clearLogs()
    H.chat("/tbx combat stat add Nope")
    t.ok(H.logged("No stat is called Nope"))
    H.chat("/tbx combat stat add Secret")
    t.ok(H.logged("hidden from add%-ons"))
    H.chat("/tbx combat stat add resist")
    t.ok(H.logged("already shown"))
    H.chat("/tbx combat stat remove MagicResistance")
    H.advance(0.5, 0.5)
    t.eq(H.combatRows()[7], "Resist=12.5")
    H.reload()
    t.eq(table.concat(C().Stats(), ","), "Resist", "remembered")
  end)

  t.test("size, position, its own strip even when the others are glued", function()
    H.boot()
    H.chat("/tbx combat")
    H.chat("/tbx combat size 150")
    t.eq(H.combatHud().children[1].children[1].children[1].children[1].style.fontSize, 18)
    H.chat("/tbx combat move 800 100")
    t.eq(H.combatHud().x, 800)
    H.chat("/tbx buffs")
    H.chat("/tbx vitals glue on")
    t.ok(H.hud() and H.combatHud(), "glued strip plus the combat strip")
    t.eq(H.combatHud().x, 800, "the combat strip stayed put")
    H.advance(1)
    H.reload()
    t.eq(H.combatHud().x, 800)
    t.eq(C().GetScale(), 150)
  end)

  t.test("settings section", function()
    H.boot()
    H.chat("/tbx config")
    H.change("toolbox_config", "show_combat", true)
    t.eq(H.combatHud().visible, true)
    H.change("toolbox_config", "combat_pet", false)
    t.eq(C().GetPet(), false)
    t.eq(H.config():Find("combat_stats").text, "Stats: MagicResistance")
    H.click("toolbox_config", "combat_right")
    t.eq(H.combatHud().x, C().HOME[1] + 10)
    H.click("toolbox_config", "combat_reset")
  end)
end
