-- Slash command registration and dispatch.
local H = require("harness")

return function(t)
  t.test("both commands are registered from ShroudOnStart", function()
    H.boot()
    t.ok(H.S.commands.toolbox, "/toolbox")
    t.ok(H.S.commands.tbx, "/tbx")
    t.eq(H.S.commands.toolbox, H.S.commands.tbx, "one dispatcher")
  end)

  t.test("constructors raise at file top level (harness enforces it)", function()
    H.boot()
    t.raises(function() Shroud.Command{ name = "x", help = "x", run = print } end, "outside a callback")
    t.raises(function() Shroud.UI.Label{ text = "x" } end, "outside a callback")
  end)

  t.test("a refused registration is reported in chat", function()
    H.boot()
    H.S.taken.tbx = "taken"
    H.S.taken.toolbox = "tooCloseToChat"
    H.clearLogs()
    H.reload()
    t.ok(H.logged("/tbx: taken"), "taken reported")
    t.ok(H.logged("/toolbox: tooCloseToChat"), "tooCloseToChat reported")
  end)

  t.test("help lists every command", function()
    H.boot()
    H.clearLogs()
    H.chat("/toolbox help")
    t.ok(H.logged("help"))
    t.ok(H.logged("/toolbox xpdetailed"))
    t.ok(H.logged("/toolbox reset"))
    t.ok(H.logged("/toolbox font"))
    t.ok(H.logged("/toolbox config"))
    t.ok(H.logged("/toolbox xp"))
    t.ok(H.logged("/toolbox spacing"))
    t.ok(H.logged("/toolbox daily"))
    t.ok(H.logged("/tbx"), "mentions the alias")
  end)

  t.test("no arguments opens the settings window; help lists commands", function()
    H.boot()
    H.clearLogs()
    H.chat("/tbx")
    t.ok(H.config() and H.config():IsShown(), "settings opened")
    t.eq(#H.logs(), 0, "no chat spam")
    H.chat("/tbx")
    t.no(H.config():IsShown(), "and closed again")
    H.chat("/tbx help")
    t.ok(H.logged("/toolbox reset"))
    t.ok(H.logged("/toolbox help %- list commands %(/toolbox alone opens the settings%)"))
  end)

  t.test("a one-time welcome line per account", function()
    H.boot()
    t.ok(H.logged("Toolbox is ready: type /toolbox to open its settings"), "first run")
    H.clearLogs()
    H.reload()
    t.no(H.logged("Toolbox is ready"), "not again")
    t.eq(H.saved("welcomed", "account"), true)
  end)

  t.test("the settings window explains itself and has a chat-commands button", function()
    H.boot()
    H.chat("/tbx")
    H.clearLogs()
    H.click("toolbox_config", "help")
    t.ok(H.logged("/toolbox xpdetailed"), "the help went to chat")
  end)

  t.test("/tbx xp opens the XP window; xpdetailed and xpd open XP Detailed", function()
    H.boot()
    H.chat("/tbx xp")
    t.ok(H.compact():IsShown(), "xp -> XP window")
    t.eq(H.compact().title, "XP")
    t.no(H.window():IsShown())
    H.chat("/tbx xpdetailed")
    t.ok(H.window():IsShown(), "xpdetailed -> XP Detailed")
    t.eq(H.window().title, "XP Detailed")
    H.chat("/tbx xpd")
    t.no(H.window():IsShown(), "xpd is the same command")
  end)

  t.test("help shows the xpd alias; the old compact command is gone", function()
    H.boot()
    H.clearLogs()
    H.chat("/tbx help")
    t.ok(H.logged("/toolbox xpdetailed %(or xpd%) %- "), "alias listed")
    H.clearLogs()
    t.no(Toolbox.Dispatch("compact"))
    t.ok(H.logged("Unknown command 'compact'"))
  end)

  t.test("xpdetailed toggles its window, alias and case-insensitive", function()
    H.boot()
    t.no(H.window():IsShown(), "starts closed")
    H.chat("/toolbox xpdetailed")
    t.ok(H.window():IsShown())
    H.chat("/tbx   XPD  ")
    t.no(H.window():IsShown())
  end)

  t.test("reset starts a new session", function()
    H.boot()
    H.gain(5000, 100)
    H.advance(60)
    t.eq(Toolbox.XP.Gained(Toolbox.session, "a"), 5000)
    H.clearLogs()
    H.chat("/tbx reset")
    t.ok(H.logged("New XP session"))
    t.eq(Toolbox.XP.Gained(Toolbox.session, "a"), 0)
    t.eq(Toolbox.session.start, ShroudTime)
  end)

  t.test("unknown subcommand", function()
    H.boot()
    H.clearLogs()
    t.no(Toolbox.Dispatch("frobnicate"))
    t.ok(H.logged("Unknown command 'frobnicate'"))
  end)

  t.test("argument parsing", function()
    H.boot()
    local w, rest = Toolbox.ParseArgs("  Reset   now please ")
    t.eq(w, "reset")
    t.eq(rest, "now please")
    w, rest = Toolbox.ParseArgs(nil)
    t.eq(w, "")
    t.eq(rest, "")
  end)

  t.test("/tbx stats lists matching readable stats and counts hidden ones", function()
    H.boot()
    H.S.stats = {
      { name = "Strength", label = "Strength", value = 50 },
      { name = "HealthMax", label = "Maximum Health", value = 812.5 },
      { name = "HealthRegen", label = "Health Regeneration", value = 3 },
      { name = "SecretHealth", label = "Secret", value = 7, hidden = true },
    }
    H.clearLogs()
    H.chat("/tbx stats HEALTH")
    t.ok(H.logged("^1 HealthMax %(Maximum Health%) = 812.5$"), H.logs()[1])
    t.ok(H.logged("^2 HealthRegen %(Health Regeneration%) = 3$"))
    t.no(H.logged("Strength"), "filtered")
    t.no(H.logged("SecretHealth"), "hidden ones aren't listed")
    t.ok(H.logged("2 readable, 1 hidden from add%-ons matching 'health' %(of 4 stats%)%."), H.lastLog())
  end)

  t.test("/tbx stats caps long lists", function()
    H.boot()
    for i = 1, 60 do H.S.stats[i] = { name = "Stat" .. i, label = "Stat " .. i, value = i } end
    H.clearLogs()
    H.chat("/tbx stats")
    t.ok(H.logged("20 more; narrow it with a word"))
    t.ok(H.logged("60 readable, 0 hidden"))
  end)

  t.test("/tbx version shows the version, build and how many copies loaded", function()
    H.boot()
    H.clearLogs()
    H.chat("/tbx version")
    t.ok(H.logged("^Toolbox 0%.1%.0, build dev; API 14; copies loaded: 1$"), H.lastLog())
    ToolboxCopies = 2                        -- as if an old copy also loaded
    H.clearLogs()
    H.chat("/tbx version")
    t.ok(H.logged("copies loaded: 2 %(remove the extra one%)"), H.lastLog())
  end)

  t.test("/tbx welcome shows it now; welcome reset shows it at the next load", function()
    H.boot()
    H.clearLogs()
    H.chat("/tbx welcome")
    t.ok(H.logged("Toolbox is ready"))
    H.chat("/tbx welcome reset")
    t.ok(H.logged("show again at the next"))
    H.clearLogs()
    H.reload()
    t.ok(H.logged("Toolbox is ready"), "shown at the reload")
    H.clearLogs()
    H.reload()
    t.no(H.logged("Toolbox is ready"), "and only once")
  end)
end
